/**
 * Flight Sim aircraft catalog.
 *
 * Every aircraft-specific number lives here — the physics engine
 * (`flightDynamics.js`) reads them and contains no type-specific constants, so
 * adding an aircraft is a catalog entry rather than a physics change.
 *
 * Units are SI throughout (metres, seconds, kilograms, Newtons, radians).
 * Knots / feet / FPM exist only in the HUD layer.
 *
 * MODEL CONVENTION — matches the bundled fleet documented in
 * `public/models/README.md`: glTF +Y-up, nose toward local −X, real-world metre
 * scale, bounding-box centre at the origin. A new model must be baked the same
 * way or given a correcting `modelOrientation`.
 *
 * CONTROL SURFACES — `controlSurfaces` maps our semantic control names onto
 * candidate node-name patterns in the GLB. Nothing here is assumed to exist:
 * `simAircraftRenderer` resolves each against the real loaded hierarchy and
 * silently skips whatever is absent. Run `node scripts/inspect-model.mjs
 * <file.glb>` to see what an asset actually contains before writing a mapping.
 */

/** Flap detents, in degrees, shared by the 747 family. */
const B747_FLAP_DETENTS = [0, 1, 5, 10, 20, 25, 30];

/**
 * Boeing 747-200B tuning.
 *
 * Figures are approximate published 747-200 performance values, rounded and
 * tuned for a stable, believable feel rather than certification accuracy. They
 * are deliberately grouped so they can be adjusted without touching physics.
 */
const BOEING_747_200B = Object.freeze({
  id: 'b747-200b',
  name: 'Boeing 747-200B',
  manufacturer: 'Boeing',
  variant: 'Rolls-Royce RB211',
  available: true,

  // ── Asset ────────────────────────────────────────────────────────────────
  // FlightGear-derived 747-8i via FlightAirMap. 204 nodes with every control
  // surface separately named, so gear/flaps/ailerons/spoilers/fans all animate.
  // LICENCE: GPL-2.0 — the only copyleft asset in the bundle. See
  // public/models/README.md and the LICENSE beside the model.
  //
  // Measured from the geometry with scripts/inspect-model.mjs: nose −X, up +Y,
  // starboard +Z — already the project's convention, so no correction needed.
  // Dimensions verified against the real 747-8 to within centimetres.
  modelUrl: '/models/flight-sim/boeing-747-8i.glb',
  /**
   * Per-part hinge lines, generated by scripts/extract-hinges.mjs.
   *
   * Required because this asset bakes geometry into mesh vertices and leaves
   * node transforms as identity — rotating a node without its hinge would swing
   * the part about the aircraft origin instead of deflecting it.
   */
  hingeMapUrl: '/models/flight-sim/boeing-747-8i.hinges.json',
  modelScale: 1.0,
  /** Extra rotation applied if a model does not follow the nose −X convention.
   *
   * The renderer adds a blanket 180° because the fleet BUNDLED WITH THIS APP is
   * baked nose-toward−X (see flights.js). This 747-8i did not come from that
   * fleet — it is the FlightAirMap asset, baked the opposite way — so it needs
   * a different rotation.
   *
   * Measured on the loaded asset rather than assumed: with the blanket 180°
   * alone the model's nose sat at compass 251° while the aircraft tracked 161°,
   * i.e. square across the direction of travel. This model's nose is baked
   * along local +X, but Cesium's heading/pitch/roll frame puts FORWARD on +Y
   * and starboard on +X — a 90° discrepancy, not the 180° the bundled fleet
   * needs. 180 + 90 = 270 net, which lands the nose exactly on track. */
  modelOrientation: { headingOffsetDeg: 90, pitchOffsetDeg: 0, rollOffsetDeg: 0 },
  /** Metres from the model origin down to the lowest airframe point (nacelles). */
  bellyOffsetM: 4.22,
  /** Metres from the model origin to the wheels with the gear extended. */
  gearHeightM: 5.6,

  // ── Geometry and mass ────────────────────────────────────────────────────
  // Measured from the asset: 76.55 m long, 68.40 m span (real 747-8: 76.3 / 68.4).
  wingspanM: 68.4,
  lengthM: 76.55,
  wingAreaM2: 554.0,
  emptyMassKg: 174_000,
  /** Simulation start mass — a mid-weight cruise load, not MTOW. */
  massKg: 285_000,
  maxMassKg: 377_800,

  // ── Propulsion ───────────────────────────────────────────────────────────
  engineCount: 4,
  /** Static thrust per engine at sea level, Newtons (RB211-524 ≈ 236 kN). */
  maxThrustPerEngineN: 236_000,
  /** Seconds for the engines to move most of the way to a new throttle setting. */
  spoolTimeS: 5.0,
  /** Fan RPM at 100% throttle, for visual fan spin where nodes exist. */
  maxFanRpm: 3_900,

  // ── Aerodynamics ─────────────────────────────────────────────────────────
  /** Lift-curve slope, per radian. ~2π is thin-aerofoil theory; real wings are lower. */
  liftSlopePerRad: 5.0,
  /** Lift coefficient at zero angle of attack. */
  cl0: 0.18,
  /** Stall angle of attack, radians (~15°). */
  stallAlphaRad: 0.262,
  /** Lift coefficient retained once fully stalled. */
  clStalled: 0.72,
  /** Parasite drag coefficient, clean. */
  cd0: 0.021,
  /** Induced-drag factor: cd = cd0 + k·cl². */
  inducedDragK: 0.045,

  // ── Control authority ────────────────────────────────────────────────────
  // A 747 is heavy and slow to respond; these are deliberately unhurried.
  /** Peak roll rate at full aileron, radians/second (~15°/s). */
  maxRollRateRadS: 0.26,
  /** Peak pitch rate at full elevator, radians/second (~5°/s). */
  maxPitchRateRadS: 0.09,
  /** Peak yaw rate at full rudder, radians/second (~3°/s). */
  maxYawRateRadS: 0.05,
  /** Seconds for a control input to reach full effect — the inertia that makes it feel heavy. */
  rollInertiaS: 2.2,
  pitchInertiaS: 2.6,
  yawInertiaS: 2.4,

  // ── Configuration effects ────────────────────────────────────────────────
  flapDetents: B747_FLAP_DETENTS,
  /** Added lift coefficient at the maximum flap detent. */
  flapLiftBonus: 0.85,
  /** Added drag coefficient at the maximum flap detent. */
  flapDragPenalty: 0.055,
  /** Added drag coefficient with the gear fully down. */
  gearDragPenalty: 0.022,
  /** Added drag coefficient with spoilers fully deployed. */
  spoilerDragPenalty: 0.048,
  /** Lift multiplier with spoilers fully deployed. */
  spoilerLiftFactor: 0.72,
  /** Seconds for the gear to travel between up and down. */
  gearTransitS: 10.0,
  /** Seconds for the flaps to travel between adjacent detents. */
  flapTransitS: 4.0,
  /** Seconds for spoilers to travel between stowed and deployed. */
  spoilerTransitS: 1.6,

  // ── Envelope ─────────────────────────────────────────────────────────────
  /** Never-exceed indicated airspeed, m/s (~365 kt). */
  vneMps: 188.0,
  /** Stall warning threshold, m/s IAS at clean configuration (~160 kt). */
  vStallCleanMps: 82.0,
  /** Typical cruise true airspeed, m/s (~490 kt TAS). */
  cruiseTasMps: 252.0,
  /** Service ceiling, metres. */
  ceilingM: 13_700,
  /** Maximum structural touchdown rate before the gear is considered overloaded, m/s. */
  maxTouchdownRateMps: 3.7,
  /** Ground steering authority at low speed, radians/second. */
  groundSteerRateRadS: 0.35,
  /** Braking deceleration on the ground, m/s². */
  brakeDecelMps2: 2.4,
  /** Rolling friction deceleration on the ground, m/s². */
  rollingFrictionMps2: 0.18,

  // ── Autopilot defaults ───────────────────────────────────────────────────
  autopilot: {
    /** Bank angle the autopilot will not exceed, radians (25°). */
    maxBankRad: 0.436,
    /** Proportional gain converting heading error to commanded bank. */
    headingGain: 1.8,
    /** Proportional gain converting altitude error to commanded vertical speed. */
    altitudeGain: 0.035,
    /** Vertical speed the autopilot will not exceed, m/s (~2000 fpm). */
    maxVerticalSpeedMps: 10.2,
    /** Cruise speed the autothrottle holds, m/s. */
    targetSpeedMps: 240.0,
  },

  // ── Camera anchors, metres in model space (x forward, y right, z up) ─────
  cameraAnchors: {
    chase: { forward: -210, right: 0, up: 62 },
    nose: { forward: 28, right: 0, up: 4.5 },
    wing: { forward: -6, right: 34, up: 6 },
    orbit: { forward: 0, right: 0, up: 10, radius: 150 },
  },

  /**
   * Semantic control name → candidate node-name patterns in the GLB.
   * Resolved against the real hierarchy at load time; missing entries are
   * skipped rather than faked. See scripts/inspect-model.mjs.
   */
  // Patterns written against the REAL node names in this asset, confirmed with
  // `node scripts/inspect-model.mjs public/models/flight-sim/boeing-747-8i.glb`.
  // FlightGear names gear NLG_* (nose) and FLG_* (fuselage) — note there is no
  // word boundary before the LG, which a naive /\blg\b/ pattern would miss.
  controlSurfaces: {
    noseGear: [/^NLG_/i],
    mainGear: [/^FLG_/i],
    wheels: [/^FLG_.*_(in|out)$/i],
    aileronLeft: [/^aileron_L$/i, /^aileron_int_L$/i],
    aileronRight: [/^aileron_R$/i, /^aileron_int_R$/i],
    elevatorLeft: [/^elevator_left/i],
    elevatorRight: [/^elevator_right/i],
    rudder: [/^rudder_/i],
    flaps: [/^doubleflaps_/i, /^external_flap_/i, /^flap_compart_/i],
    spoilers: [/^speedbrake_/i],
    engineFans: [/^blades_\d/i],
    beacons: [/^beacon\./i],
  },
});

/** Every aircraft the simulator knows about, keyed by id. */
const CATALOG = Object.freeze({
  [BOEING_747_200B.id]: BOEING_747_200B,
});

/** The aircraft selected when the planner opens. */
export const DEFAULT_AIRCRAFT_ID = BOEING_747_200B.id;

/**
 * Every catalog entry, in display order.
 *
 * @returns {Array<object>} Aircraft definitions.
 */
export function listAircraft() {
  return Object.values(CATALOG);
}

/**
 * Only the aircraft users may currently select.
 *
 * Entries can be authored ahead of their asset landing by setting
 * `available: false`; they stay out of the picker until the model exists.
 *
 * @returns {Array<object>} Selectable aircraft definitions.
 */
export function listAvailableAircraft() {
  return listAircraft().filter((a) => a.available);
}

/**
 * Look up one aircraft.
 *
 * @param {string} id - Catalog id.
 * @returns {object|null} The definition, or null when unknown.
 */
export function getAircraft(id) {
  return CATALOG[id] || null;
}

/**
 * Validate a catalog entry.
 *
 * The physics engine divides by several of these, so a missing or zero value
 * would surface as NaN telemetry mid-flight rather than as a clear error at
 * startup. Exported so a test can assert every shipped entry is well-formed.
 *
 * @param {object} aircraft - Candidate definition.
 * @returns {string[]} Problems found; empty means valid.
 */
export function validateAircraft(aircraft) {
  const problems = [];
  if (!aircraft || typeof aircraft !== 'object') return ['aircraft is not an object'];

  const requiredStrings = ['id', 'name', 'manufacturer', 'modelUrl'];
  for (const key of requiredStrings) {
    if (typeof aircraft[key] !== 'string' || !aircraft[key]) problems.push(`${key} must be a non-empty string`);
  }

  // Anything used as a divisor or a rate must be finite and positive.
  const requiredPositive = [
    'massKg', 'wingAreaM2', 'wingspanM', 'maxThrustPerEngineN', 'engineCount',
    'liftSlopePerRad', 'stallAlphaRad', 'cd0', 'vneMps', 'vStallCleanMps',
    'maxRollRateRadS', 'maxPitchRateRadS', 'maxYawRateRadS',
    'rollInertiaS', 'pitchInertiaS', 'yawInertiaS',
    'gearTransitS', 'flapTransitS', 'spoilerTransitS',
  ];
  for (const key of requiredPositive) {
    const value = aircraft[key];
    if (!Number.isFinite(value) || value <= 0) problems.push(`${key} must be a positive finite number`);
  }

  if (!Array.isArray(aircraft.flapDetents) || aircraft.flapDetents.length === 0) {
    problems.push('flapDetents must be a non-empty array');
  } else {
    if (aircraft.flapDetents[0] !== 0) problems.push('flapDetents must start at 0');
    for (let i = 1; i < aircraft.flapDetents.length; i += 1) {
      if (aircraft.flapDetents[i] <= aircraft.flapDetents[i - 1]) {
        problems.push('flapDetents must be strictly ascending');
        break;
      }
    }
  }

  if (aircraft.vStallCleanMps >= aircraft.vneMps) problems.push('vStallCleanMps must be below vneMps');

  const anchors = aircraft.cameraAnchors;
  if (!anchors || typeof anchors !== 'object') {
    problems.push('cameraAnchors is required');
  } else {
    for (const view of ['chase', 'nose', 'wing', 'orbit']) {
      const a = anchors[view];
      if (!a || !Number.isFinite(a.forward) || !Number.isFinite(a.right) || !Number.isFinite(a.up)) {
        problems.push(`cameraAnchors.${view} needs finite forward/right/up`);
      }
    }
  }

  const ap = aircraft.autopilot;
  if (!ap || typeof ap !== 'object') {
    problems.push('autopilot config is required');
  } else {
    for (const key of ['maxBankRad', 'headingGain', 'altitudeGain', 'maxVerticalSpeedMps', 'targetSpeedMps']) {
      if (!Number.isFinite(ap[key]) || ap[key] <= 0) problems.push(`autopilot.${key} must be a positive finite number`);
    }
  }

  return problems;
}
